#!/usr/bin/env bash

# (14/10/2024)	Wrapper for ProtEvol.

GPU=1
ProtEvol=./Simulation.py
ProjectBaseName=Thioredoxin
PopSize=100
SimTime=100
CompScale=2
StartSeed=240

SimDir=/net/vacuole1/linuxhome/ph-group/sam/NOBINFBACKUP-Documents/ProteinEvol/Yeast/MyAnalysis/alternative_folding/simulation/proteins
# TargetStruct="ATTSSAAATTATTSSATTAAHHHHHHHHHHHHHHHTAAAASSSTTSSAAABATTSABAAHHHHHHHHHHHSAAATTAAAHHHHHHHHHHHHHHTHHHHAATTHHHHHAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHTTATTTHHHHHHHHHHHHHHHHHHTAASHHHHHHHHHHHHSAAAASSSHHHHHHHGGGAAAAHHHHHHTTSSAAAAAASEEEEETTTTEEEEEAATTAAAAAEEEEEEEEETTTEEEEEEEEESATTATTHHHHHHHHHHHHAHHHHHHHIIIIIHHHTAAA"
# InitSeq="CAAGACCAGGGCTTACATGGCAACATGAATGGAGACGGAGCACCGTATCCTAATTTCAATTACAATATGCATCAGTCGATGGTACGATGTCTGTTCCAGAGACTAGGAAATTCGCATTGGTATTTAGCCCACTACGGCGACTGCGCAAAGCGCAATGATCAGAATGAATACATACAGCCATTTATGAAGTTCTGTTGGTGGCAAGTAGGTACTCAGGTCTCTCCGGAAATGAAGGACCCCTGGTCATTGATAGCCAAAGACGCATACAACATAAATTTCGGGCATAGAGCAACATGTGGCACGCACGAGTTACATGGTAAATTTCCAGAATGGGTGCATTGGTTCCACATGATGGCCAACCAATGGGCCGAACATTTCGCACCAGTGATTACGCAGCTGCTCTCATTAGAACGTGCTAAACACCGTAATTATTTTTGGACTCAGGCGTGGTGGACGTCACACGCGATGTCCTTTTTTCAGCAATGTAAGATATGGCCTGGAGCTGCCTATTATCATGAGAAATATCAGGCTGACATGATGCCGATCAAGGATGACGGATGGTTTGAGTGTTTTTTCTGTGAACTGCGATGGATGCCGAGATGGCGAATGGCCGCCGACTACACTCATCAAAAGATGCCCGAACCCCCGAATCAATGCGACATAGACCACGATACGAACGACGTAAAATGCAGGTACATACCAGGCGAGGGTAAGGATATTAGCTACCAATTTATAATGACCGAACACGATGGGGGCCACTTGCACATAGCTTATGAAGTTTCTGGTGCCCATAACCTTCGGTTTGCATACCACTGGTGGGCAGATTGGGTTGCCTGTAGCGACGCGACGTGGTTCTGGCGGAGGTCTGTAAGACAAACAGCAGCTCATACAAAGGTCAAA"
TargetStruct=`cat ${SimDir}/Q8NBQ5.sss`
InitSeq=`cat ${SimDir}/Q55C17.dna`

i=1
for SelectTargetP in 0.1 0.25 0.5 0.75 0.9;
do
	for MutRate in 0.0001 0.005 0.001;
	do

		Seed=$((StartSeed+i))
		ProjectName=${ProjectBaseName}${i}

		CUDA_VISIBLE_DEVICES=$GPU $ProtEvol -p $ProjectName -s $Seed -m $MutRate -N $PopSize -t $SimTime -C $CompScale -T $TargetStruct -i $InitSeq -pst $SelectTargetP > /linuxhome/tmp/sam/protevol/${ProjectName}.log

		i=$((i+1))

	done
done